site_name: Segmantic
site_description: Semantic segmentation and image-to-image translation based on AI
repo_url: https://github.com/dyollb/segmantic

theme:
  name: material
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


nav:
  - Home: "index.md"
  - Usage Examples:
      - ToDo: "examples/ToDo.ipynb"


plugins:
  - search
  - mkdocs-jupyter
