[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "segmantic"
authors = [{name = "Bryn Lloyd", email = "lloyd@itis.swiss"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = ">=3.7"
dynamic = ["version", "description"]

dependencies = [
    "monai",
    "torch",
    "torchvision",
    "pytorch-lightning",
    "typer",
    "matplotlib",
    "dominate",
    "scikit-learn",
    "tensorboard",
    "itk>=5.3rc3"
]

[project.optional-dependencies]
test = [
  "pytest",
  "mypy",
]
dev = [
  "black",
  "flake8",
  "isort",
  "mypy",
  "pre-commit",
]

[project.urls]
Home = "https://github.com/dyollb/segmantic.git"

[tool.isort]
profile = "black"

[tool.mypy]
disallow_untyped_defs = false
warn_unused_configs = true
exclude = "/pix2pix_cyclegan/"

[[tool.mypy.overrides]]
module = "segmantic.prepro.*"
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "itk.*,PIL,matplotlib.*,torch,torchvision.*,numba,setuptools,pytest,typer.*,click,colorama,nibabel,sklearn.*"
ignore_missing_imports = true
