name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check format
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "src"
      - name: Pip install test
        run: pip install -e ".[test]"
      - name: Static analysis
        run: mypy .
